# Copyright (c) 2023, Cisco Systems, Inc. and/or its affiliates.
# All rights reserved.
# See LICENSE file in this distribution.
# SPDX-License-Identifier: Apache-2.0

services:
  tiedie-sample-app:
    image: tiedie-java-sample-app:latest
    entrypoint: ["java","-jar","/app.jar", "--spring.config.location=config/application.properties"]
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./sample-java-app/config:/config
    networks:
      - gateway

networks:
  gateway:
    name: gateway_default
    external: true

