services:
  tiedie-sample-app:
    image: tiedie-sample-app:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./sample-python-app/config:/config
